service_account = { type = "service_account", project_id = "pantospjt", private_key_id = "33c5d4feb2765cae359a042b793fca6206299736", private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCoRkHXFvBf0Wyx
lfs5c9CQvWnRPYs7Z7jqYo1jFEhi8XsP4Wm8LwZ0dWMBMswxdppzPRleFTuDBGPy
kuZB/cDmBL4GSTcf6Afv1PvisnyYDkdW7dOszagqwPBvAZlGr2QKRiipZQ0rVp4P
ocmK8fAyJcwv4/u5o7nfgE5Nc77uIIOUboXNbl3nO+ncWuPIiWDtpjEk5LQHmyIf
VJ5voMAEm8jQGrQgjHD2V7tFyQpsFIBICwUjOCGPcQ2G7WjI7zvcfT0ZDrLFdJrJ
QF9JI4tZscZ6GQWwGiIWwASeXXWlXwt8yRRmvFogXgtTphQGTwQU//yzK/dPMD7Q
g/TGjMCrAgMBAAECgf8E0UxkeamOK/y7Z9EScwnXCKbYeDfSK4cAX4OnzZRYs8gq
q99JzaURntkwE70tNXXEScs18q8DbfnW7zejc5sR1Weq1p/X12ePMimKqD5KQNRZ
MfCYtWVkIB/ZVawJIqs8qTtSPZb4Q5SOV1Bu5BrimRCTvSTqZo+hVnR5bHGzHqcc
LjdYXjp/IFisu/1fI93KdvdWl9EsPSGbYJUVWpTzNZrqwcF16BAGxsXQhJuqup5F
hYcNEQkxQ8btfS6RPNBeGnH/VkcePjfa+PvM7uDCEcgVYykFDCpbyss08GAA8VYv
z1seiZWlq87QGzlUcWqH+Is3yLVOd6v/WMNqIC0CgYEA6JbkWrZlSoJ/OmtTR6EW
wOmBmap9XcmuLc0NdjBqbHrvEk/zA0v8Z/f7d7kYI0Az0+gl5m+yPThnJod3V3ar
dAa92tccC0SbXpYZlPDZ3aYVqWWffvQrFsxOzbYTxCv0QnLSkoxaXBc+/penPGKR
2hWdt0tGR7aeQeLHaYX0rc0CgYEAuTYq6gLeO5QYuOQI46Z/PXEASUyy7jmqI51S
TFs6g21dRzriPz8kCKQMSwEeE6mbWAQ3xIFsoKVyT4JdT62/Pl1s6dRaGlLMt9MY
4dubGmTcKN0FGRAvTK7KeuzPzv9HOgEKL1vrA3i1kszxxIG2o/7zyZzqVbB0buD2
gInMcFcCgYEAkC8yQnW9lxIMsvdjeg0HoPFgURVagDCNVIFALhtXbgZLfCupt0p8
nysgbZiFuRyMxHmuPQrTEJaNg1oJBmRfZx7ixO4CyY1vT5R3KVihhoD1/rwrwrS0
nX5r/6Q23q5szmCF3yk4vsv+Vi9HEez9A5fQ3JbCa6RuuONPwT+0baUCgYBY5kAo
/OFw1YAcVxBRPRy8AB50EIWeRT1+RMg48F0gsoDgbMomM4d3Qk7IPawTIgj3cWbX
QoxCe8dnlJp3YV13cN6TSiNJmU68OW4rEv7a52ipkJUe157sfsWfxUVmBTBKDi+2
VbdzfiAha4/sk5p4EysvLcto//6TLhYD0qC3lwKBgQCEJAVpZsN9BQq0bPvPtyql
W3EHgLp0oGiNRABjYSEgf30o2DMCbE6fuClIWg5f+TlGhnYAsCZXWODXw30NgkHm
jkuVGLX4OyDCXfJ1u6jEebf1CKr2NJfGCy9iqU7bANjKWG2UlsSKSOw4x8WlxfG8
TAvSW2qyMlh0eP8vYdc+hQ==
-----END PRIVATE KEY-----""", client_email = "spreadsheetpeeper@pantospjt.iam.gserviceaccount.com", client_id = "102681641762357522814", auth_uri = "https://accounts.google.com/o/oauth2/auth", token_uri = "https://oauth2.googleapis.com/token", auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs", client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/spreadsheetpeeper%40pantospjt.iam.gserviceaccount.com", universe_domain = "googleapis.com"}