[theme]
base = "light"
primaryColor = "#1976D2"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E3ECF7"
textColor = "#222222"
linkColor = "#1565C0"
codeBackgroundColor = "#A72B2A"
font = "sans-serif"
headingFont = "sans-serif"
baseRadius = "0.5rem"
borderColor = "#A72B2A"
showWidgetBorder = true
baseFontSize = 18
showSidebarBorder = true